"""empty message

Revision ID: 390b3eb19e7b
Revises: d90fa7b18ade
Create Date: 2023-01-21 03:06:35.626692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390b3eb19e7b'
down_revision = 'd90fa7b18ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
